---
- name: Upgrade Debian 10 to Debian 11
  hosts: all
  become: yes
  tasks:
    - name: Backup current sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.backup

    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb https://deb.debian.org/debian bookworm main
          deb-src https://deb.debian.org/debian bookworm main
          deb https://deb.debian.org/debian-security bookworm-security main
          deb-src https://deb.debian.org/debian-security bookworm-security main
          deb https://deb.debian.org/debian bookworm-updates main
          deb-src https://deb.debian.org/debian bookworm-updates main
          
    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list.d/google-cloud.list
        content: |
          deb https://packages.cloud.google.com/apt google-compute-engine-bookworm-stable main
          deb https://packages.cloud.google.com/apt cloud-sdk-bookworm main
          
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade to Debian 11
      apt:
        upgrade: dist

    - name: Reboot the system
      reboot:
        reboot_timeout: 500

    - name: Check the Debian version after reboot
      command: lsb_release -a
      register: lsb_release_output

    - name: Display Debian version
      debug:
        msg: "{{ lsb_release_output.stdout_lines }}"
