---
- name: Upgrade Debian 10 to Debian 11
  hosts: all
  become: yes
  tasks:
    - name: Backup current sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.backup

    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
          deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

          deb https://deb.debian.org/debian-security bookworm-security main contrib non-free
          deb-src https://deb.debian.org/debian-security bookworm-security main contrib non-free

    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list.d/cloud-sdk.list
        content: |
          deb http://packages.cloud.google.com/apt cloud-sdk-bookworm main
          
    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list.d/google-cloud-ops-agent.list
        content: |
          deb https://packages.cloud.google.com/apt google-cloud-ops-agent-bookworm-all main
          
    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list.d/google-cloud.list
        content: |
          deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-bookworm main
          
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade to Debian 11
      apt:
        upgrade: dist

    - name: Reboot the system
      reboot:
        reboot_timeout: 300

    - name: Check the Debian version after reboot
      command: lsb_release -a
      register: lsb_release_output

    - name: Display Debian version
      debug:
        msg: "{{ lsb_release_output.stdout_lines }}"
