---
- name: Upgrade Debian 10 to Debian 11
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is up to date
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Backup current sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.backup

    - name: Update sources.list to Debian 11 repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ bullseye main contrib non-free
          deb-src http://deb.debian.org/debian/ bullseye main contrib non-free
          
          deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
          deb-src http://deb.debian.org/debian/ bullseye-updates main contrib non-free
          
          deb http://security.debian.org/ bullseye-security main contrib non-free
          deb-src http://security.debian.org/ bullseye-security main contrib non-free

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade to Debian 11
      apt:
        upgrade: dist

    - name: Reboot the system
      reboot:
        reboot_timeout: 1000

    - name: Check the Debian version after reboot
      command: lsb_release -a
      register: lsb_release_output

    - name: Display Debian version
      debug:
        msg: "{{ lsb_release_output.stdout_lines }}"





