---
- name: Upgrade Debian 10 to Debian 11
  hosts: all
  become: true
  tasks:
    - name: Backup current sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.backup

    - name: Update APT sources.list to Debian 11
      replace:
        path: /etc/apt/sources.list
        regexp: '^deb http://deb.debian.org/debian buster'
        replace: 'deb http://deb.debian.org/debian bullseye'
      notify: Update APT sources

    - name: Update APT sources.list to Debian 11 (security updates)
      replace:
        path: /etc/apt/sources.list
        regexp: '^deb http://security.debian.org/debian-security buster'
        replace: 'deb http://security.debian.org/debian-security bullseye-security'
      notify: Update APT sources

    - name: Update APT sources.list to Debian 11 (updates)
      replace:
        path: /etc/apt/sources.list
        regexp: '^deb http://deb.debian.org/debian buster-updates'
        replace: 'deb http://deb.debian.org/debian bullseye-updates'
      notify: Update APT sources

    - name: Update APT sources.list to Debian 11 (backports)
      replace:
        path: /etc/apt/sources.list
        regexp: '^deb http://deb.debian.org/debian buster-backports'
        replace: 'deb http://deb.debian.org/debian bullseye-backports'
      notify: Update APT sources

    - name: Add missing GPG keys for Google Cloud packages
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add missing GPG key for Debian
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: C0BA5CE6DC6315A3
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Perform a minimal upgrade of existing packages
      apt:
        upgrade: safe
        update_cache: yes

    - name: Upgrade the system to Debian 11
      apt:
        upgrade: dist
        update_cache: yes

    - name: Remove obsolete packages
      apt:
        autoremove: yes

  handlers:
    - name: Update APT sources
      apt:
        update_cache: yes
        cache_valid_time: 3600
        cache_valid_time: 3600

