---
- name: Display OS release information
  hosts: all
  become: yes  # Use become to run the command with elevated privileges if necessary
  tasks:
    - name: Run cat command to get OS release info
      command: cat /etc/*-release
      register: os_release_output

    - name: Display OS release info
      debug:
        msg: "{{ os_release_output.stdout }}"



