---
- name: Run command to get OS release information
  hosts: all
  gather_facts: no
  tasks:
    - name: Get OS release information
      command: cat /etc/*-release
      register: os_release_info

    - name: Show OS release information
      debug:
        msg: "{{ os_release_info.stdout }}"





