---
- name: Upgrade Debian to the next release
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Backup current sources.list
      command: cp /etc/apt/sources.list /etc/apt/sources.list.backup
      ignore_errors: yes  # Ignore errors if the file does not exist

    - name: Create backup directory for sources.list.d
      file:
        path: /etc/apt/sources.list.d.backup
        state: directory

    - name: Backup sources.list.d directory
      command: >
        cp -r /etc/apt/sources.list.d/* /etc/apt/sources.list.d.backup/
      ignore_errors: yes  # Ignore errors if the directory does not exist

    - name: Update sources.list to the next release repositories
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
          deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

          deb https://deb.debian.org/debian-security bookworm-security main contrib non-free
          deb-src https://deb.debian.org/debian-security bookworm-security main contrib non-free

    - name: Update additional APT repositories to the next release
      lineinfile:
        path: "{{ item }}"
        regexp: '^deb '
        line: "{{ item | regex_replace('buster', 'bookworm') }}"
      loop:
        - /etc/apt/sources.list.d/cloud-sdk.list
        - /etc/apt/sources.list.d/google-cloud-ops-agent.list
        - /etc/apt/sources.list.d/google-cloud-packages-archive-keyring.list
      ignore_errors: yes  # Ignore errors if files do not exist

    - name: Clean package cache
      apt:
        autoclean: yes

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade to the next release
      apt:
        upgrade: dist

    - name: Perform full upgrade
      apt:
        full_upgrade: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Reboot the system
      reboot:
        reboot_timeout: 1000

    - name: Check the Debian version after reboot
      command: lsb_release -a
      register: lsb_release_output

    - name: Display Debian version
      debug:
        msg: "{{ lsb_release_output.stdout_lines }}"
