---
- name: Upgrade Debian 10 to Debian 11
  hosts: all
  become: yes
  tasks:
    - name: Check the Debian version after reboot
      command: lsb_release -a
      register: lsb_release_output

    - name: Display Debian version
      debug:
        msg: "{{ lsb_release_output.stdout_lines }}"
