- name: Remove user
  hosts: all
  become: true  # Grant sudo/root privileges
  vars_prompt:
    - name: "username"
      prompt: "Please enter the username to remove"
      private: no

  tasks:
    - name: Remove user and home directory
      user:
        name: "{{ username }}"
        state: absent
        remove: yes  # remove the user's home directory
