---
- name: Ping hosts and display detailed output
  hosts: all
  tasks:
    - name: Ping the host
      ping:
      register: ping_result

    - name: Display detailed ping result
      debug:
        msg: |
          Ping result for host {{ inventory_hostname }}:
          - Success: {{ ping_result.ping }}
          - Raw output: {{ ping_result }}

