---
- name: Update all packages on Debian-based systems
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
    
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
